// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: grpc/ModuleBalancing.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MD5Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MD5Request) Reset() {
	*x = MD5Request{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MD5Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MD5Request) ProtoMessage() {}

func (x *MD5Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MD5Request.ProtoReflect.Descriptor instead.
func (*MD5Request) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{0}
}

type MD5Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MD5           string                 `protobuf:"bytes,1,opt,name=MD5,proto3" json:"MD5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MD5Response) Reset() {
	*x = MD5Response{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MD5Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MD5Response) ProtoMessage() {}

func (x *MD5Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MD5Response.ProtoReflect.Descriptor instead.
func (*MD5Response) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{1}
}

func (x *MD5Response) GetMD5() string {
	if x != nil {
		return x.MD5
	}
	return ""
}

type DataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Serveraddress string                 `protobuf:"bytes,2,opt,name=serveraddress,proto3" json:"serveraddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{2}
}

func (x *DataRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DataRequest) GetServeraddress() string {
	if x != nil {
		return x.Serveraddress
	}
	return ""
}

type DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Completed     bool                   `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{3}
}

func (x *DataResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DataResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type StorerecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Heartbeat     string                 `protobuf:"bytes,1,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Serveraddress string                 `protobuf:"bytes,2,opt,name=serveraddress,proto3" json:"serveraddress,omitempty"`
	Partnumber    string                 `protobuf:"bytes,3,opt,name=partnumber,proto3" json:"partnumber,omitempty"`
	Modulenames   []string               `protobuf:"bytes,4,rep,name=modulenames,proto3" json:"modulenames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorerecordRequest) Reset() {
	*x = StorerecordRequest{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorerecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorerecordRequest) ProtoMessage() {}

func (x *StorerecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorerecordRequest.ProtoReflect.Descriptor instead.
func (*StorerecordRequest) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{4}
}

func (x *StorerecordRequest) GetHeartbeat() string {
	if x != nil {
		return x.Heartbeat
	}
	return ""
}

func (x *StorerecordRequest) GetServeraddress() string {
	if x != nil {
		return x.Serveraddress
	}
	return ""
}

func (x *StorerecordRequest) GetPartnumber() string {
	if x != nil {
		return x.Partnumber
	}
	return ""
}

func (x *StorerecordRequest) GetModulenames() []string {
	if x != nil {
		return x.Modulenames
	}
	return nil
}

type StorerecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isok          bool                   `protobuf:"varint,1,opt,name=isok,proto3" json:"isok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorerecordResponse) Reset() {
	*x = StorerecordResponse{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorerecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorerecordResponse) ProtoMessage() {}

func (x *StorerecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorerecordResponse.ProtoReflect.Descriptor instead.
func (*StorerecordResponse) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{5}
}

func (x *StorerecordResponse) GetIsok() bool {
	if x != nil {
		return x.Isok
	}
	return false
}

type IntegrityVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrityVerificationRequest) Reset() {
	*x = IntegrityVerificationRequest{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrityVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrityVerificationRequest) ProtoMessage() {}

func (x *IntegrityVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrityVerificationRequest.ProtoReflect.Descriptor instead.
func (*IntegrityVerificationRequest) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{6}
}

func (x *IntegrityVerificationRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type IntegrityVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	Crc64         string                 `protobuf:"bytes,3,opt,name=crc64,proto3" json:"crc64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrityVerificationResponse) Reset() {
	*x = IntegrityVerificationResponse{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrityVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrityVerificationResponse) ProtoMessage() {}

func (x *IntegrityVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrityVerificationResponse.ProtoReflect.Descriptor instead.
func (*IntegrityVerificationResponse) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{7}
}

func (x *IntegrityVerificationResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *IntegrityVerificationResponse) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *IntegrityVerificationResponse) GetCrc64() string {
	if x != nil {
		return x.Crc64
	}
	return ""
}

type ModuleDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serveraddress string                 `protobuf:"bytes,1,opt,name=serveraddress,proto3" json:"serveraddress,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleDownloadRequest) Reset() {
	*x = ModuleDownloadRequest{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleDownloadRequest) ProtoMessage() {}

func (x *ModuleDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleDownloadRequest.ProtoReflect.Descriptor instead.
func (*ModuleDownloadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{8}
}

func (x *ModuleDownloadRequest) GetServeraddress() string {
	if x != nil {
		return x.Serveraddress
	}
	return ""
}

func (x *ModuleDownloadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ModuleDownloadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ModulePushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Completed     bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModulePushResponse) Reset() {
	*x = ModulePushResponse{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModulePushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModulePushResponse) ProtoMessage() {}

func (x *ModulePushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModulePushResponse.ProtoReflect.Descriptor instead.
func (*ModulePushResponse) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{9}
}

func (x *ModulePushResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ModulePushResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadRequest_Information
	//	*UploadRequest_ChunkData
	Data          isUploadRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{10}
}

func (x *UploadRequest) GetData() isUploadRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadRequest) GetInformation() *Finformation {
	if x != nil {
		if x, ok := x.Data.(*UploadRequest_Information); ok {
			return x.Information
		}
	}
	return nil
}

func (x *UploadRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadRequest_Data interface {
	isUploadRequest_Data()
}

type UploadRequest_Information struct {
	Information *Finformation `protobuf:"bytes,1,opt,name=information,proto3,oneof"`
}

type UploadRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadRequest_Information) isUploadRequest_Data() {}

func (*UploadRequest_ChunkData) isUploadRequest_Data() {}

type Finformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	Crc64         string                 `protobuf:"bytes,3,opt,name=crc64,proto3" json:"crc64,omitempty"`
	MUnix         string                 `protobuf:"bytes,4,opt,name=MUnix,proto3" json:"MUnix,omitempty"`
	CUnix         string                 `protobuf:"bytes,5,opt,name=CUnix,proto3" json:"CUnix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finformation) Reset() {
	*x = Finformation{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finformation) ProtoMessage() {}

func (x *Finformation) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finformation.ProtoReflect.Descriptor instead.
func (*Finformation) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{11}
}

func (x *Finformation) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Finformation) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Finformation) GetCrc64() string {
	if x != nil {
		return x.Crc64
	}
	return ""
}

func (x *Finformation) GetMUnix() string {
	if x != nil {
		return x.MUnix
	}
	return ""
}

func (x *Finformation) GetCUnix() string {
	if x != nil {
		return x.CUnix
	}
	return ""
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{12}
}

func (x *UploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AnalyzingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Fbytes        []byte                 `protobuf:"bytes,2,opt,name=fbytes,proto3" json:"fbytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzingRequest) Reset() {
	*x = AnalyzingRequest{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzingRequest) ProtoMessage() {}

func (x *AnalyzingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzingRequest.ProtoReflect.Descriptor instead.
func (*AnalyzingRequest) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{13}
}

func (x *AnalyzingRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AnalyzingRequest) GetFbytes() []byte {
	if x != nil {
		return x.Fbytes
	}
	return nil
}

type AnalyzingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Modulename     []string               `protobuf:"bytes,1,rep,name=modulename,proto3" json:"modulename,omitempty"`
	Analyzingerror []string               `protobuf:"bytes,2,rep,name=analyzingerror,proto3" json:"analyzingerror,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzingResponse) Reset() {
	*x = AnalyzingResponse{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzingResponse) ProtoMessage() {}

func (x *AnalyzingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzingResponse.ProtoReflect.Descriptor instead.
func (*AnalyzingResponse) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{14}
}

func (x *AnalyzingResponse) GetModulename() []string {
	if x != nil {
		return x.Modulename
	}
	return nil
}

func (x *AnalyzingResponse) GetAnalyzingerror() []string {
	if x != nil {
		return x.Analyzingerror
	}
	return nil
}

type ExpirationPushRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Serveraddress    string                 `protobuf:"bytes,1,opt,name=serveraddress,proto3" json:"serveraddress,omitempty"`
	Maxretentiondays int64                  `protobuf:"varint,2,opt,name=maxretentiondays,proto3" json:"maxretentiondays,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExpirationPushRequest) Reset() {
	*x = ExpirationPushRequest{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpirationPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpirationPushRequest) ProtoMessage() {}

func (x *ExpirationPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpirationPushRequest.ProtoReflect.Descriptor instead.
func (*ExpirationPushRequest) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{15}
}

func (x *ExpirationPushRequest) GetServeraddress() string {
	if x != nil {
		return x.Serveraddress
	}
	return ""
}

func (x *ExpirationPushRequest) GetMaxretentiondays() int64 {
	if x != nil {
		return x.Maxretentiondays
	}
	return 0
}

type ExpirationPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partnumber    string                 `protobuf:"bytes,1,opt,name=partnumber,proto3" json:"partnumber,omitempty"`
	Modulename    []string               `protobuf:"bytes,2,rep,name=modulename,proto3" json:"modulename,omitempty"`
	Heartbeat     string                 `protobuf:"bytes,3,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpirationPushResponse) Reset() {
	*x = ExpirationPushResponse{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpirationPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpirationPushResponse) ProtoMessage() {}

func (x *ExpirationPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpirationPushResponse.ProtoReflect.Descriptor instead.
func (*ExpirationPushResponse) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{16}
}

func (x *ExpirationPushResponse) GetPartnumber() string {
	if x != nil {
		return x.Partnumber
	}
	return ""
}

func (x *ExpirationPushResponse) GetModulename() []string {
	if x != nil {
		return x.Modulename
	}
	return nil
}

func (x *ExpirationPushResponse) GetHeartbeat() string {
	if x != nil {
		return x.Heartbeat
	}
	return ""
}

var File_grpc_ModuleBalancing_proto protoreflect.FileDescriptor

const file_grpc_ModuleBalancing_proto_rawDesc = "" +
	"\n" +
	"\x1agrpc/ModuleBalancing.proto\x12\x0fModuleBalancing\"\f\n" +
	"\n" +
	"MD5Request\"\x1f\n" +
	"\vMD5Response\x12\x10\n" +
	"\x03MD5\x18\x01 \x01(\tR\x03MD5\"K\n" +
	"\vDataRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12$\n" +
	"\rserveraddress\x18\x02 \x01(\tR\rserveraddress\"F\n" +
	"\fDataResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\bR\tcompleted\"\x9a\x01\n" +
	"\x12StorerecordRequest\x12\x1c\n" +
	"\theartbeat\x18\x01 \x01(\tR\theartbeat\x12$\n" +
	"\rserveraddress\x18\x02 \x01(\tR\rserveraddress\x12\x1e\n" +
	"\n" +
	"partnumber\x18\x03 \x01(\tR\n" +
	"partnumber\x12 \n" +
	"\vmodulenames\x18\x04 \x03(\tR\vmodulenames\")\n" +
	"\x13StorerecordResponse\x12\x12\n" +
	"\x04isok\x18\x01 \x01(\bR\x04isok\":\n" +
	"\x1cIntegrityVerificationRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"e\n" +
	"\x1dIntegrityVerificationResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\x12\x14\n" +
	"\x05crc64\x18\x03 \x01(\tR\x05crc64\"q\n" +
	"\x15ModuleDownloadRequest\x12$\n" +
	"\rserveraddress\x18\x01 \x01(\tR\rserveraddress\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"L\n" +
	"\x12ModulePushResponse\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\"{\n" +
	"\rUploadRequest\x12A\n" +
	"\vinformation\x18\x01 \x01(\v2\x1d.ModuleBalancing.finformationH\x00R\vinformation\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x06\n" +
	"\x04data\"\x80\x01\n" +
	"\ffinformation\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\x12\x14\n" +
	"\x05crc64\x18\x03 \x01(\tR\x05crc64\x12\x14\n" +
	"\x05MUnix\x18\x04 \x01(\tR\x05MUnix\x12\x14\n" +
	"\x05CUnix\x18\x05 \x01(\tR\x05CUnix\"D\n" +
	"\x0eUploadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"F\n" +
	"\x10analyzingRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x16\n" +
	"\x06fbytes\x18\x02 \x01(\fR\x06fbytes\"[\n" +
	"\x11analyzingResponse\x12\x1e\n" +
	"\n" +
	"modulename\x18\x01 \x03(\tR\n" +
	"modulename\x12&\n" +
	"\x0eanalyzingerror\x18\x02 \x03(\tR\x0eanalyzingerror\"i\n" +
	"\x15ExpirationPushRequest\x12$\n" +
	"\rserveraddress\x18\x01 \x01(\tR\rserveraddress\x12*\n" +
	"\x10maxretentiondays\x18\x02 \x01(\x03R\x10maxretentiondays\"v\n" +
	"\x16ExpirationPushResponse\x12\x1e\n" +
	"\n" +
	"partnumber\x18\x01 \x01(\tR\n" +
	"partnumber\x12\x1e\n" +
	"\n" +
	"modulename\x18\x02 \x03(\tR\n" +
	"modulename\x12\x1c\n" +
	"\theartbeat\x18\x03 \x01(\tR\theartbeat2\xf8\x02\n" +
	"\x06Module\x12K\n" +
	"\x06Upload\x12\x1e.ModuleBalancing.UploadRequest\x1a\x1f.ModuleBalancing.UploadResponse(\x01\x12R\n" +
	"\tAnalyzing\x12!.ModuleBalancing.analyzingRequest\x1a\".ModuleBalancing.analyzingResponse\x12v\n" +
	"\x15IntegrityVerification\x12-.ModuleBalancing.IntegrityVerificationRequest\x1a..ModuleBalancing.IntegrityVerificationResponse\x12U\n" +
	"\x04Push\x12&.ModuleBalancing.ModuleDownloadRequest\x1a#.ModuleBalancing.ModulePushResponse0\x012q\n" +
	"\x0eExpirationpush\x12_\n" +
	"\n" +
	"Expiration\x12&.ModuleBalancing.ExpirationPushRequest\x1a'.ModuleBalancing.ExpirationPushResponse0\x012o\n" +
	"\vStorerecord\x12`\n" +
	"\x11Updatestorerecord\x12#.ModuleBalancing.StorerecordRequest\x1a$.ModuleBalancing.StorerecordResponse(\x012\x96\x01\n" +
	"\vClientCheck\x12@\n" +
	"\x03MD5\x12\x1b.ModuleBalancing.MD5Request\x1a\x1c.ModuleBalancing.MD5Response\x12E\n" +
	"\x04Data\x12\x1c.ModuleBalancing.DataRequest\x1a\x1d.ModuleBalancing.DataResponse0\x01B\aZ\x05/grpcb\x06proto3"

var (
	file_grpc_ModuleBalancing_proto_rawDescOnce sync.Once
	file_grpc_ModuleBalancing_proto_rawDescData []byte
)

func file_grpc_ModuleBalancing_proto_rawDescGZIP() []byte {
	file_grpc_ModuleBalancing_proto_rawDescOnce.Do(func() {
		file_grpc_ModuleBalancing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_ModuleBalancing_proto_rawDesc), len(file_grpc_ModuleBalancing_proto_rawDesc)))
	})
	return file_grpc_ModuleBalancing_proto_rawDescData
}

var file_grpc_ModuleBalancing_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_grpc_ModuleBalancing_proto_goTypes = []any{
	(*MD5Request)(nil),                    // 0: ModuleBalancing.MD5Request
	(*MD5Response)(nil),                   // 1: ModuleBalancing.MD5Response
	(*DataRequest)(nil),                   // 2: ModuleBalancing.DataRequest
	(*DataResponse)(nil),                  // 3: ModuleBalancing.DataResponse
	(*StorerecordRequest)(nil),            // 4: ModuleBalancing.StorerecordRequest
	(*StorerecordResponse)(nil),           // 5: ModuleBalancing.StorerecordResponse
	(*IntegrityVerificationRequest)(nil),  // 6: ModuleBalancing.IntegrityVerificationRequest
	(*IntegrityVerificationResponse)(nil), // 7: ModuleBalancing.IntegrityVerificationResponse
	(*ModuleDownloadRequest)(nil),         // 8: ModuleBalancing.ModuleDownloadRequest
	(*ModulePushResponse)(nil),            // 9: ModuleBalancing.ModulePushResponse
	(*UploadRequest)(nil),                 // 10: ModuleBalancing.UploadRequest
	(*Finformation)(nil),                  // 11: ModuleBalancing.finformation
	(*UploadResponse)(nil),                // 12: ModuleBalancing.UploadResponse
	(*AnalyzingRequest)(nil),              // 13: ModuleBalancing.analyzingRequest
	(*AnalyzingResponse)(nil),             // 14: ModuleBalancing.analyzingResponse
	(*ExpirationPushRequest)(nil),         // 15: ModuleBalancing.ExpirationPushRequest
	(*ExpirationPushResponse)(nil),        // 16: ModuleBalancing.ExpirationPushResponse
}
var file_grpc_ModuleBalancing_proto_depIdxs = []int32{
	11, // 0: ModuleBalancing.UploadRequest.information:type_name -> ModuleBalancing.finformation
	10, // 1: ModuleBalancing.Module.Upload:input_type -> ModuleBalancing.UploadRequest
	13, // 2: ModuleBalancing.Module.Analyzing:input_type -> ModuleBalancing.analyzingRequest
	6,  // 3: ModuleBalancing.Module.IntegrityVerification:input_type -> ModuleBalancing.IntegrityVerificationRequest
	8,  // 4: ModuleBalancing.Module.Push:input_type -> ModuleBalancing.ModuleDownloadRequest
	15, // 5: ModuleBalancing.Expirationpush.Expiration:input_type -> ModuleBalancing.ExpirationPushRequest
	4,  // 6: ModuleBalancing.Storerecord.Updatestorerecord:input_type -> ModuleBalancing.StorerecordRequest
	0,  // 7: ModuleBalancing.ClientCheck.MD5:input_type -> ModuleBalancing.MD5Request
	2,  // 8: ModuleBalancing.ClientCheck.Data:input_type -> ModuleBalancing.DataRequest
	12, // 9: ModuleBalancing.Module.Upload:output_type -> ModuleBalancing.UploadResponse
	14, // 10: ModuleBalancing.Module.Analyzing:output_type -> ModuleBalancing.analyzingResponse
	7,  // 11: ModuleBalancing.Module.IntegrityVerification:output_type -> ModuleBalancing.IntegrityVerificationResponse
	9,  // 12: ModuleBalancing.Module.Push:output_type -> ModuleBalancing.ModulePushResponse
	16, // 13: ModuleBalancing.Expirationpush.Expiration:output_type -> ModuleBalancing.ExpirationPushResponse
	5,  // 14: ModuleBalancing.Storerecord.Updatestorerecord:output_type -> ModuleBalancing.StorerecordResponse
	1,  // 15: ModuleBalancing.ClientCheck.MD5:output_type -> ModuleBalancing.MD5Response
	3,  // 16: ModuleBalancing.ClientCheck.Data:output_type -> ModuleBalancing.DataResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_ModuleBalancing_proto_init() }
func file_grpc_ModuleBalancing_proto_init() {
	if File_grpc_ModuleBalancing_proto != nil {
		return
	}
	file_grpc_ModuleBalancing_proto_msgTypes[10].OneofWrappers = []any{
		(*UploadRequest_Information)(nil),
		(*UploadRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_ModuleBalancing_proto_rawDesc), len(file_grpc_ModuleBalancing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_grpc_ModuleBalancing_proto_goTypes,
		DependencyIndexes: file_grpc_ModuleBalancing_proto_depIdxs,
		MessageInfos:      file_grpc_ModuleBalancing_proto_msgTypes,
	}.Build()
	File_grpc_ModuleBalancing_proto = out.File
	file_grpc_ModuleBalancing_proto_goTypes = nil
	file_grpc_ModuleBalancing_proto_depIdxs = nil
}
